### ISSUE TITLE
url lib.error

### ISSUE THREAD

**Issue by sgoggins42** [pmorrell/SNPMeta#2]
Tom, fix this.

```
Traceback (most recent call last):
  File "SNPMeta.py", line 26, in <module>
    from snpmeta.SNPAnnotation.blast_search import BlastSearch
  File "/panfs/roc/groups/9/morrellp/goggi015/SNPMeta/snpmeta/SNPAnnotation/blast_search.py", line 8, in <module>
    from urllib.error import HTTPError
ImportError: No module named error
```

-Shawn

**Comment by TomJKono** [comment]
What version of Python are you using?

**Comment by mojaveazure** [comment]
@sgoggins42 Use Python 3, not 2
